{"name": "test_4", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: \n Element {FakeElement.DoesNotExist} was not present after 0.5 seconds!", "trace": "self = <test_suite.MyTestSuite testMethod=test_4>\n\n    @pytest.mark.expected_failure\n    def test_4(self):\n        print(\"\\n(This test fails on purpose)\")\n        self.open(\"https://xkcd.com/1670/\")\n>       self.assert_element(\"FakeElement.DoesNotExist\", timeout=0.5)\n\ntest_suite.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nc:\\users\\covid19\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\seleniumbase\\fixtures\\base_case.py:4774: in assert_element\n    self.wait_for_element_visible(selector, by=by, timeout=timeout)\nc:\\users\\covid19\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\seleniumbase\\fixtures\\base_case.py:3144: in wait_for_element_visible\n    self.driver, selector, by, timeout)\nc:\\users\\covid19\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\seleniumbase\\fixtures\\page_actions.py:299: in wait_for_element_visible\n    timeout_exception(NoSuchElementException, message)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nexception = <class 'selenium.common.exceptions.NoSuchElementException'>, message = '\\n Element {FakeElement.DoesNotExist} was not present after 0.5 seconds!'\n\n    def timeout_exception(exception, message):\n        exc, message = s_utils.format_exc(exception, message)\n>       raise exc(message)\nE       selenium.common.exceptions.NoSuchElementException: Message: \nE        Element {FakeElement.DoesNotExist} was not present after 0.5 seconds!\n\nc:\\users\\covid19\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\seleniumbase\\fixtures\\page_actions.py:117: NoSuchElementException"}, "attachments": [{"name": "stdout", "source": "524c304a-08e3-4822-9101-b26ee7811504-attachment.txt", "type": "text/plain"}], "start": 1596657863191, "stop": 1596657873044, "uuid": "7df501cb-1d49-419e-ada0-9ada136c01a9", "historyId": "e8e717e4c5a79cb6ae11c730559b74c4", "testCaseId": "f5447bbd3d112ac037cbc600b5c3e115", "fullName": "test_suite.MyTestSuite#test_4", "labels": [{"name": "tag", "value": "expected_failure"}, {"name": "suite", "value": "test_suite"}, {"name": "subSuite", "value": "MyTestSuite"}, {"name": "host", "value": "CAL4PFMXT2"}, {"name": "thread", "value": "22576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_suite"}]}